[phases.setup]
nixPkgs = ["gcc", "python39", "python39Packages.pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --worker-class gevent -w 1 app:app"
